# Generated by Django 3.2.7 on 2022-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('preview', models.TextField(max_length=254)),
                ('article', models.TextField()),
                ('author', models.CharField(max_length=54)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog_source', models.CharField(blank=True, default='', max_length=254)),
                ('source_url', models.URLField(blank=True, default='', max_length=1024)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
